#ifndef _GPIO_CONFIG_H_
#define _GPIO_CONFIG_H_


#ifdef CONFIG_CUBICAT_S3
#define CONFIG_ENABLE_LCD 1
#define CONFIG_ENABLE_TOUCH 1
#define CONFIG_LCD_WIDTH 320
#define CONFIG_LCD_HEIGHT 240
#define CONFIG_LCD_SDA 7
#define CONFIG_LCD_SCL 5
#define CONFIG_LCD_RST 6
#define CONFIG_LCD_DC 4
#define CONFIG_TOUCH_SDA_GPIO 21
#define CONFIG_TOUCH_SCL_GPIO 47
#define CONFIG_TOUCH_RST_GPIO 17
#define CONFIG_TOUCH_INT_GPIO 18

#define CONFIG_PDM_MICPHONE 1
#define CONFIG_SPEAKER_BCK_GPIO 11
#define CONFIG_SPEAKER_WS_GPIO 10
#define CONFIG_SPEAKER_DATA_GPIO 12
#define CONFIG_SPEAKER_EN_GPIO 13
#define CONFIG_SPEAKER_SAMPLE_RATE 16000
#define CONFIG_SPEAKER_BIT_WIDTH 16

#define CONFIG_MIC_BCK_GPIO 8
#define CONFIG_MIC_WS_GPIO -1
#define CONFIG_MIC_DATA_GPIO 9
#define CONFIG_MIC_SAMPLE_RATE 16000
#define CONFIG_MIC_BIT_WIDTH 16
#endif

#endif